
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Random;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author HP
 */
public class accountInformation extends javax.swing.JFrame {

    /**
     * Creates new form accountInformation
     */
    
    Connection con;
    ResultSet rs;
    PreparedStatement pst;
    public accountInformation() {
        super("Create New Account");
        initComponents();
        con = DBConnect.Connection();
        randomAccountNumber();
        randomAccountID();
        randomPassword();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextFieldAccountNumber = new javax.swing.JTextField();
        jTextFieldAccountID = new javax.swing.JTextField();
        jTextFieldPassword = new javax.swing.JTextField();
        jRadioButtonMale = new javax.swing.JRadioButton();
        jRadioButtonFemale = new javax.swing.JRadioButton();
        jTextFieldName = new javax.swing.JTextField();
        jComboBoxAccountType = new javax.swing.JComboBox<>();
        jComboBoxReligon = new javax.swing.JComboBox<>();
        jTextFieldMobileNumber = new javax.swing.JTextField();
        jTextFieldAddress = new javax.swing.JTextField();
        jTextFieldNIDNumber = new javax.swing.JTextField();
        jTextFieldBCNumber = new javax.swing.JTextField();
        jRadioButtonOther = new javax.swing.JRadioButton();
        jButtonCreateAccount = new javax.swing.JButton();
        jButtonClear = new javax.swing.JButton();
        back = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jTextFieldQuestion = new javax.swing.JTextField();
        jTextFieldanswer = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jTextFieldCreditAmount = new javax.swing.JTextField();
        jDateChooserBirthDate = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Account Information - eBanking");
        setEnabled(false);
        setPreferredSize(new java.awt.Dimension(1366, 768));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\Desktop\\BMS\\banklogo.png")); // NOI18N

        jLabel1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 51));
        jLabel1.setText("Account Number : ");

        jLabel3.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 153, 51));
        jLabel3.setText("Account ID : ");

        jLabel4.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 153, 51));
        jLabel4.setText("Password : ");

        jLabel5.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 153, 51));
        jLabel5.setText("Account Type : ");

        jLabel6.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 153, 51));
        jLabel6.setText("Name : ");

        jLabel7.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 153, 51));
        jLabel7.setText("Date of Birth : ");

        jLabel8.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 153, 51));
        jLabel8.setText("Gender : ");

        jLabel9.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 153, 51));
        jLabel9.setText("Religon : ");

        jLabel10.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 153, 51));
        jLabel10.setText("Mobile Number : ");

        jLabel11.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 153, 51));
        jLabel11.setText("Address : ");

        jLabel12.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 153, 51));
        jLabel12.setText("NID Number : ");

        jLabel13.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 153, 51));
        jLabel13.setText("BC Number : ");

        jTextFieldAccountNumber.setEditable(false);
        jTextFieldAccountNumber.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jTextFieldAccountNumber.setForeground(new java.awt.Color(0, 153, 51));
        jTextFieldAccountNumber.setEnabled(false);

        jTextFieldAccountID.setEditable(false);
        jTextFieldAccountID.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jTextFieldAccountID.setForeground(new java.awt.Color(0, 153, 51));
        jTextFieldAccountID.setEnabled(false);

        jTextFieldPassword.setEditable(false);
        jTextFieldPassword.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jTextFieldPassword.setForeground(new java.awt.Color(0, 153, 51));
        jTextFieldPassword.setEnabled(false);

        buttonGroup1.add(jRadioButtonMale);
        jRadioButtonMale.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jRadioButtonMale.setForeground(new java.awt.Color(0, 153, 51));
        jRadioButtonMale.setText("Male");
        jRadioButtonMale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMaleActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButtonFemale);
        jRadioButtonFemale.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jRadioButtonFemale.setForeground(new java.awt.Color(0, 153, 51));
        jRadioButtonFemale.setText("Female");

        jTextFieldName.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jTextFieldName.setForeground(new java.awt.Color(0, 153, 51));

        jComboBoxAccountType.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jComboBoxAccountType.setForeground(new java.awt.Color(0, 153, 51));
        jComboBoxAccountType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Account Type", "Current", "Savings" }));

        jComboBoxReligon.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jComboBoxReligon.setForeground(new java.awt.Color(0, 153, 51));
        jComboBoxReligon.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Religon", "Islam", "Hindu", "Buddho", "Khristan" }));

        jTextFieldMobileNumber.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jTextFieldMobileNumber.setForeground(new java.awt.Color(0, 153, 51));

        jTextFieldAddress.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jTextFieldAddress.setForeground(new java.awt.Color(0, 153, 51));

        jTextFieldNIDNumber.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jTextFieldNIDNumber.setForeground(new java.awt.Color(0, 153, 51));

        jTextFieldBCNumber.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jTextFieldBCNumber.setForeground(new java.awt.Color(0, 153, 51));

        buttonGroup1.add(jRadioButtonOther);
        jRadioButtonOther.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jRadioButtonOther.setForeground(new java.awt.Color(0, 153, 51));
        jRadioButtonOther.setText("Other");

        jButtonCreateAccount.setBackground(new java.awt.Color(204, 255, 204));
        jButtonCreateAccount.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButtonCreateAccount.setForeground(new java.awt.Color(0, 153, 0));
        jButtonCreateAccount.setText("Create Account");
        jButtonCreateAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCreateAccountActionPerformed(evt);
            }
        });

        jButtonClear.setBackground(new java.awt.Color(204, 255, 204));
        jButtonClear.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButtonClear.setForeground(new java.awt.Color(0, 153, 0));
        jButtonClear.setText("Clear");
        jButtonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClearActionPerformed(evt);
            }
        });

        back.setBackground(new java.awt.Color(204, 255, 204));
        back.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        back.setForeground(new java.awt.Color(0, 153, 0));
        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 153, 0));
        jLabel14.setText("Security Question : ");

        jLabel15.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 153, 0));
        jLabel15.setText("Answer : ");

        jTextFieldQuestion.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jTextFieldQuestion.setForeground(new java.awt.Color(0, 153, 0));

        jTextFieldanswer.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jTextFieldanswer.setForeground(new java.awt.Color(0, 153, 0));

        jButton4.setBackground(new java.awt.Color(204, 255, 204));
        jButton4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(0, 153, 0));
        jButton4.setText("Print");

        jLabel16.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 153, 0));
        jLabel16.setText("Credit Amount : ");

        jTextFieldCreditAmount.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jTextFieldCreditAmount.setForeground(new java.awt.Color(0, 153, 0));

        jDateChooserBirthDate.setForeground(new java.awt.Color(0, 153, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addContainerGap(997, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonCreateAccount)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonClear)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4)
                        .addGap(18, 18, 18)
                        .addComponent(back))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel16))
                                .addGap(21, 21, 21))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldAccountNumber)
                            .addComponent(jTextFieldAccountID)
                            .addComponent(jTextFieldPassword)
                            .addComponent(jComboBoxAccountType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldQuestion)
                            .addComponent(jTextFieldanswer, javax.swing.GroupLayout.DEFAULT_SIZE, 403, Short.MAX_VALUE)
                            .addComponent(jTextFieldCreditAmount))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jRadioButtonMale)
                                .addGap(37, 37, 37)
                                .addComponent(jRadioButtonFemale)
                                .addGap(10, 10, 10)
                                .addComponent(jRadioButtonOther))
                            .addComponent(jTextFieldName)
                            .addComponent(jTextFieldMobileNumber)
                            .addComponent(jTextFieldAddress)
                            .addComponent(jTextFieldNIDNumber)
                            .addComponent(jTextFieldBCNumber)
                            .addComponent(jComboBoxReligon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jDateChooserBirthDate, javax.swing.GroupLayout.DEFAULT_SIZE, 403, Short.MAX_VALUE))))
                .addGap(36, 36, 36))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jTextFieldAccountNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTextFieldAccountID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTextFieldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jComboBoxAccountType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(jTextFieldQuestion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(jTextFieldanswer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel16))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jDateChooserBirthDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jRadioButtonMale)
                            .addComponent(jRadioButtonFemale)
                            .addComponent(jRadioButtonOther))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jComboBoxReligon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jTextFieldMobileNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jTextFieldAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(jTextFieldNIDNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldCreditAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(jTextFieldBCNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonClear)
                    .addComponent(back)
                    .addComponent(jButtonCreateAccount)
                    .addComponent(jButton4))
                .addGap(475, 475, 475))
        );

        setBounds(0, 0, 1363, 712);
    }// </editor-fold>//GEN-END:initComponents

    
    
    public void randomAccountNumber(){
        Random ran = new Random();
        jTextFieldAccountNumber.setText("" + ran.nextInt(10000 + 1));
    }
    
    
    public void randomAccountID(){
        Random ran = new Random();
        jTextFieldAccountID.setText("" + ran.nextInt(1000000 + 1));
    }
    
    
    public void randomPassword(){
        Random ran = new Random();
        jTextFieldPassword.setText("" + ran.nextInt(1000000 + 1));
    }
    
    
    public void balance(){
        String query = "insert into dbbalanceinformation(Name,AccountNumber,PhoneNumber,Balance)values(?, ?, ?, ?)";
        try{
            pst = con.prepareStatement(query);
            pst.setString(1, jTextFieldName.getText());
            pst.setString(2, jTextFieldAccountNumber.getText());
            pst.setString(3, jTextFieldMobileNumber.getText());
            pst.setString(4, jTextFieldCreditAmount.getText());
            pst.execute();
        }
        
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    
    private void jRadioButtonMaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonMaleActionPerformed

    private void jButtonCreateAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCreateAccountActionPerformed
        // TODO add your handling code here:
        String query = "insert into dbaccountinformation(AccountNumber,AccountID,Password,AccountType,SecurityQuestion,Answer,Name,DateofBirth,Gender,Religon,MobileNumber,Address,NIDNumber,BCNumber,CreditAmount)values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
        try{
            pst = con.prepareStatement(query);
             pst.setString(1, jTextFieldAccountNumber.getText());
             pst.setString(2, jTextFieldAccountID.getText());
             pst.setString(3, jTextFieldPassword.getText());
             pst.setString(4, (String)jComboBoxAccountType.getSelectedItem());
             pst.setString(5, jTextFieldQuestion.getText());
             pst.setString(6, jTextFieldanswer.getText());
             pst.setString(7, jTextFieldName.getText());
             pst.setString(8, ((JTextField)jDateChooserBirthDate.getDateEditor().getUiComponent()).getText());
             jRadioButtonMale.setActionCommand("Male");
             jRadioButtonFemale.setActionCommand("Female");
             jRadioButtonOther.setActionCommand("Other");
             pst.setString(9, buttonGroup1.getSelection().getActionCommand());
             pst.setString(10, (String)jComboBoxReligon.getSelectedItem());
             pst.setString(11, jTextFieldMobileNumber.getText());
             pst.setString(12, jTextFieldAddress.getText());
             pst.setString(13, jTextFieldNIDNumber.getText());
             pst.setString(14, jTextFieldBCNumber.getText());
             pst.setString(15, jTextFieldCreditAmount.getText());
             pst.execute();
             JOptionPane.showMessageDialog(null, "Account has been created!");
             balance();
            
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButtonCreateAccountActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        Login obj = new Login();
        obj.setVisible(true);
    }//GEN-LAST:event_backActionPerformed

    private void jButtonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearActionPerformed
        // TODO add your handling code here:
        jTextFieldAccountNumber.setText("");
        jTextFieldAccountID.setText("");
        jTextFieldPassword.setText("");
        jTextFieldQuestion.setText("");
        jTextFieldanswer.setText("");
        jTextFieldCreditAmount.setText("");
        jTextFieldName.setText("");
        jTextFieldMobileNumber.setText("");
        jTextFieldAddress.setText("");
        jTextFieldNIDNumber.setText("");
        jTextFieldBCNumber.setText("");
    }//GEN-LAST:event_jButtonClearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(accountInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(accountInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(accountInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(accountInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new accountInformation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButtonClear;
    private javax.swing.JButton jButtonCreateAccount;
    private javax.swing.JComboBox<String> jComboBoxAccountType;
    private javax.swing.JComboBox<String> jComboBoxReligon;
    private com.toedter.calendar.JDateChooser jDateChooserBirthDate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButtonFemale;
    private javax.swing.JRadioButton jRadioButtonMale;
    private javax.swing.JRadioButton jRadioButtonOther;
    private javax.swing.JTextField jTextFieldAccountID;
    private javax.swing.JTextField jTextFieldAccountNumber;
    private javax.swing.JTextField jTextFieldAddress;
    private javax.swing.JTextField jTextFieldBCNumber;
    private javax.swing.JTextField jTextFieldCreditAmount;
    private javax.swing.JTextField jTextFieldMobileNumber;
    private javax.swing.JTextField jTextFieldNIDNumber;
    private javax.swing.JTextField jTextFieldName;
    private javax.swing.JTextField jTextFieldPassword;
    private javax.swing.JTextField jTextFieldQuestion;
    private javax.swing.JTextField jTextFieldanswer;
    // End of variables declaration//GEN-END:variables
}
